server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://eureka.bluebox.org.cn:8761/eureka/


spring:
  application:
    name: hello-service

swagger:
  enabled: true
  title: 服务端测试demo
  description: 服务端测试demo 描述信息
  version: 1.0
  base-package: com.thgy
  base-path: /**
  exclude-path: /error, /ops/**
  # 鉴权配置, 保持默认配置即可
#  authorization:
#    name: Authorization
#    key-name: token # 鉴权传递的Header参数
#    auth-regex: ^.*$ # 需要开启鉴权URL的正则, 默认^.*$匹配所有URL