spring:
  datasource:
    url: jdbc:mysql://192.168.12.151:3306/udevforums-user?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 50
    initialSize: 1
    maxWait: 60000
    minIdle: 1

ushare:
  user:
# A user create hooks for user creation, when api call failure, local user will be not created!
#    createhooks: "POST http://localhost:8061/test/ec1, POST http://localhost:8061/test/ec2, POST http://localhost:8061/test/ec3"
    # createflows: "POST http://localhost:8080/api/account/initUserAccount?userId={userId},POST http://localhost:8080/api/relation/user/initUserRelationData?userId={userId}"
    createflows: "POST http://192.168.12.151:8080/api/account/initUserAccount?userId={userId}"
    access-host: 'localhost,0:0:0:0:0:0:0:1,127.0.0.1,192.168'
    password:
      staticSalt: .
      algorithmName: SHA
      numberOfIterations: 2
      saltFieldName: username
      rule: '.{8,}'
      rule-desc: 'Password need more that 8 characters'
    blacklist:
      enable: true
    whitelist:
      enable: false
    gifCode:
      enable: false
    # 默认头像
    defaultAvator: "https://xuanwuyun.com/FnDqL6spdWrhf7_6d1gRGNsc5RMU"


# 敏感词效验
contentAuth:
  url: http://192.168.12.222:8063/contentauth