server:
  port: 8761

eureka:
  instance:
    hostname: eureka.bluebox.org.cn
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#logging:
#  config: classpath:log4j2.xml

